### ISSUE TITLE
存在tools.jar但仍然报错

### ISSUE THREAD

**Issue by htfc786** [tommy811/jCat#2]
开发者您好，我使用了您的项目但是遇到了问题

我按照您的方法运行项目，  
出现如下报错：  
```
八月 10, 2024 4:28:40 下午 org.coderead.jcat.JCatLoader findToolsByJAVAHOME
信息: find tools.jar by JAVA_HOME:F:\Java\jdk1.8\lib\tools.jar
java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated
```
并且，在程序输出的位置，存在tools.jar文件：  
![image](https://github.com/user-attachments/assets/70f1df90-4ecd-4858-b55d-94f0581d52f2)  
我使用管理员权限运行，但仍未解决：  
![image](https://github.com/user-attachments/assets/6c17d8d9-fbeb-490b-9ce1-388de40234ee)

### 备注：
- 系统：Windows 10 1809 build 17763.6054  
- JDK版本：java version "1.8.0_202"  
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)  
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)  

不好意思打扰您了，感谢您开发出如此棒的项目！

**Comment by luban-uncle** [comment]
把你的jre/bin下面的 attach.dll 文件拷贝到jdk/bin下面 来就可以初始化了

**Comment by htfc786** [comment]
感谢大叔，问题解决
![image](https://github.com/user-attachments/assets/33d26a62-536b-4175-87a7-3afce51f141b)
前几天没看邮件，感谢大叔的开源！

**Comment by htfc786** [comment]
感谢大叔，问题解决
![image](https://github.com/user-attachments/assets/33d26a62-536b-4175-87a7-3afce51f141b)
前几天没看邮件，回复稍晚，抱歉，抱歉
感谢大叔的开源！
